export const ADD_NEW_CONTECT_REQUEST = "ADD_NEW_CONTECT_REQUEST";
export const ADD_NEW_CONTECT_REQUEST_SUCCESS = "ADD_NEW_CONTECT_REQUEST_SUCCESS";
export const ADD_NEW_CONTECT_REQUEST_FAILED = "ADD_NEW_CONTECT_REQUEST_FAILED";
export const DELETE_CONTECT_REQUEST = "DELETE_CONTECT_REQUEST";
export const EDIT_CONTECT_REQUEST = "EDIT_CONTECT_REQUEST";
export const DELETE_CONTECT_REQUEST_SUCCESS = "DELETE_CONTECT_REQUEST_SUCCESS";

export const SET_LOADING = "SET_LOADING";
